# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Deploy BPB API to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        appdir: "bpb-api/build/libs"
        procfile: "web: java -jar bpb-api-1.0.0.jar"
        heroku_api_key: ${{secrets.BPB_HEROKU_API_KEY}}
        heroku_app_name: "BPB API"
        heroku_email: "kristo.isberg@gmail.com"
